# Generated by Django 2.2.16 on 2020-10-13 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BarCodeApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
